### ISSUE TITLE
Please review

### ISSUE THREAD

**Issue by avermeulen** [codex-academy/angular-intro#1]
@SteveBarnett ,

This is a basic intro for Pretty and Denver - basically of the back of the Angular intro video which is unfortunately a bit out of date. But this is easier than creating my own video at this stage.

Just to give them a basic idea of Angular - the idea is to extend this to have a MongoDB backend that store the todos using ngResource.

Please review and make suggestions.

**Comment by SteveBarnett** [comment]
@avermeulen Reviewed and made some tiny changes.

Also opened https://github.com/codex-academy/angular-intro/pull/2 for some suggestions for updates.
